name: deploy - development (dispatch)
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Git Fetch / Pull / Docker Build
        with:
          REF: ${{ github.ref_name }}
          run: |
            echo $REF
            echo ${{ github.ref_name }}
