name: PR Comment

on:
  pull_request_target:
    paths:
      - '**/*' 

jobs:
  comment:
    if: github.repository == 'Bananamilk452/ci-test-react'
    runs-on: ubuntu-latest
    env:
      BASE_SHA: ${{ github.event.pull_request.base.sha }}
      HEAD_SHA: ${{ github.event.pull_request.head.sha }}

    steps:
      - name: Checkout repository
        with:
          ref: "${{ env.HEAD_SHA }}"
          fetch-depth: 0
        uses: actions/checkout@v2

      - name: Identify changed files
        id: changes
        run: |
          {
            echo "files<<EOF"
            git diff --name-only ${{ env.BASE_SHA }}...${{ env.HEAD_SHA }}
            echo 'EOF'
          } >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR with changed files
        uses: actions/github-script@v7
        with:
          script: |
            const files = `${{ steps.changes.outputs.files }}`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `<details><summary>Changed files (${files.split('\n').length})</summary>${files.split('\n').join('\n').map((f) => `- [f](https://github.com/${content.repo.owner}/${content.repo.repo}/${process.env.HEAD_SHA}/${f})`)}</details>`,
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
