name: PR Comment

on:
  pull_request_target:
    branches:
      - main

jobs:
  comment:
    if: github.repository == "ci-test-react"
    runs-on: ubuntu-latest
    permissions: read-all
    env:
      BASE_SHA: ${{ github.event.pull_request.base.sha }}
      HEAD_SHA: ${{ github.event.pull_request.head.sha }}

    steps:
      - name: Checkout repository
        with:
          ref: "${{ env.HEAD_SHA }}"
        uses: actions/checkout@v2

      - name: Identify changed files
        id: changes
        run: |
          # Use the GitHub API to get the list of changed files
          # documentation: https://docs.github.com/rest/commits/commits#compare-two-commits
          DIFF_DOCUMENTS=$(gh api repos/{owner}/{repo}/compare/${{ env.BASE_SHA }}...${{ env.HEAD_SHA }} \
            --jq '.files | .[] | select(.status|IN("added", "modified", "renamed", "copied", "changed")) | .filename')
          echo "files=${DIFF_DOCUMENTS}" >> $GITHUB_OUTPUT

      - name: Comment on PR with changed files
        uses: actions/github-script@v7
        with:
          script: |
            const files = `${{ steps.changes.outputs.files }}`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `<details><summary>Changed files (${files.split('\n').length})</summary>${files.split('\n').join('\n')}</details>`,
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
