name: Print Branch Name

on:
  workflow_dispatch:

jobs:
  print-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract branch name
        run: echo "::set-output name=branch_name::${GITHUB_REF##*/}"

      - name: Print branch name
        run: echo "Branch name is ${{ steps.extract-branch-name.outputs.branch_name }}"
